In [1]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [6]:
arr = np.array(list1)
#print(type(arr))
arr

array([1, 2, 3, 4, 5])

In [7]:
arr[0] # first element

1

In [8]:
arr[-1] # last element

5

In [9]:
len(arr)

5

In [10]:
arr.size

5

In [12]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
arr2 = np.array(matrix)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
len(arr2) # number of rows

3

In [16]:
arr2.size # total number of elements

9

In [17]:
len(arr2[0])  # number of cols in 1st row

3

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [32]:
arr = np.zeros(5) # default type is float64
arr

array([0., 0., 0., 0., 0.])

In [33]:
arr = np.zeros(5, dtype='int32')
arr

array([0, 0, 0, 0, 0], dtype=int32)

In [34]:
arr.dtype

dtype('int32')

In [35]:
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
arr = np.eye(4) # Identity matrix
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
arr.T # Transpose of a Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [43]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [49]:
np.random.seed(42)
np.random.rand(4) # Uniform distribution over [0,1]

array([0.50672601, 0.0575307 , 0.62757999, 0.13255253])

In [50]:
np.random.seed(42)
np.random.rand(4)

array([0.50672601, 0.0575307 , 0.62757999, 0.13255253])

In [51]:
np.random.randn(4) # Standard normal distribution

array([ 0.31506457, -0.40282244, -2.63330372,  0.2019705 ])

In [52]:
np.random.rand(4,5)

array([[0.5780087 , 0.48817441, 0.33596388, 0.14081627, 0.89144247],
       [0.08631166, 0.84751223, 0.52961562, 0.55026078, 0.84846109],
       [0.15899783, 0.29799614, 0.81780804, 0.97789759, 0.93313332],
       [0.31041422, 0.48133056, 0.38278433, 0.87424921, 0.36350472]])

In [53]:
np.random.randn(4,5)

array([[-0.40319217, -0.09986537,  0.25798659, -0.2052044 , -0.49902061],
       [ 2.77815098,  0.06200738, -0.96401567,  0.93484827, -1.27397971],
       [-0.78526833, -0.43116654, -1.27524129, -0.045631  , -0.507225  ],
       [-0.28122485, -0.02355569,  0.77267138, -0.85679597,  0.61445721]])

#### Random integers

In [59]:
np.random.randint(1, 100) # a number between low (inclusive) and high (exclusive)

28

In [80]:
np.random.randint(1, 100, 10)

array([28, 23, 62, 73, 67, 16, 10, 48, 87, 93])

In [82]:
arr = np.random.randint(1, 100, 10)
arr

array([82,  5, 69, 91, 46, 41, 69, 10, 17, 98])

In [83]:
arr.min()

5

In [84]:
arr.max()

98

In [85]:
arr.mean()

52.8

In [86]:
arr.argmin()

1

In [88]:
arr.argmax()

9

In [66]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
arr.shape

(25,)

In [70]:
arr2 = arr.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
arr2.shape

(5, 5)

In [74]:
arr2 = arr2.reshape(25,1)
arr2

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [75]:
arr2.shape

(25, 1)

In [76]:
arr2.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [77]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
arr2 = arr.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [89]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr[5]

5

In [91]:
arr[-1]

10

In [92]:
arr[2:6]

array([2, 3, 4, 5])

In [93]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr[5] = 100
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10])

In [96]:
arr[1:5] = 200 # Broadcasting
arr

array([  0, 200, 200, 200, 200, 100,   6,   7,   8,   9,  10])

In [98]:
arr[:] = 123
arr

array([123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123])

In [100]:
arr2 = arr
print(arr)
print(arr2)
arr is arr2 # True because they are same object

[123 123 123 123 123 123 123 123 123 123 123]
[123 123 123 123 123 123 123 123 123 123 123]


True

In [101]:
arr2 = arr.copy()
print(arr)
print(arr2)
arr is arr2 # False because they are differnt objects

[123 123 123 123 123 123 123 123 123 123 123]
[123 123 123 123 123 123 123 123 123 123 123]


False

In [102]:
arr = np.array([1,2,3,4,5])
arr[1] # 2nd element

2

In [106]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
arr[1] # 2nd Row

array([4, 5, 6])

In [108]:
arr[0][2]

3

In [109]:
arr[0,2]

3

In [110]:
arr[:2, 1:] # rows 0 and 1, cols from 1 till end

array([[2, 3],
       [5, 6]])

In [111]:
arr[:2,:2] # first 2 rows and first 2 cols

array([[1, 2],
       [4, 5]])